### ISSUE TITLE
Question about updated allelicimbalance vignette

### ISSUE THREAD

**Issue by DM2016** [pappewaio/AllelicImbalance#7] opened 2016-01-10 01:45 UTC
Hello, 
I have some issues with the AllelicImbalance package.  In section 2.6 (adding genotype information), I am trying to run the following commands and in order to get the following result:
```
#infer and add genotype require declaration of the reference allele 
ref(a.simple) <- randomRef(a.simple) 
genotype(a.simple) <- inferGenotypes(a.simple) 

#access to genotype information requires not only the information about the #reference allele but also the alternative allele 
alt(a.simple) <- inferAltAllele(a.simple) 
genotype(a.simple)[,1:4] 

##         [,1]      [,2]   [,3]  [,4] 
## [1,] "T/G" "T/G" NA "T/G" 
## [2,] "G/C" "G/C" "G/C" "G/C" 
## [3,] "G/A" "G/A" "G/A" "G/A" 
```
However, when I run the command, I am getting the following errors:
```
> ref(a.simple) <- randomRef(a.simple)
Error in .local(x, ...) : 
  genotype matrix is not present as assay in  ASEset object, see '?inferGenotypes' 

> genotype(a.simple) <- inferGenotypes(a.simple)

> alt(a.simple) <- inferAltAllele(a.simple)
Error in inferAltAllele(a.simple) : there is no metadata column for mcols() with the name 'ref'

> genotype(a.simple)[,1:4]

               individual1 individual2 individual3 individual4
rs2230159      "G/A"       "G/A"       NA          "G/A"      
chr17_79478331 "T/G"       "T/G"       "T/G"       "T/G"      
chr17_79478334 "C/G"       "C/G"       "C/G"       "C/G"
```
Also, for some reason, when I write the code for a.simple, the name of my first assay is countsUnknown instead of countsPlus and later when I run the strand information section in section 2.3, I get 5 assays instead of the 4 that the vignette shows, as well as the following warning message:
```
> library(VariantAnnotation)
> pathToVcf <- paste(pathToFiles,"/ERP000101.vcf",sep="")
> VCF <- readVcf(pathToVcf,"hg19")
found header lines for 3 ‘fixed’ fields: ALT, QUAL, FILTER 
found header lines for 24 ‘info’ fields: DP, DP4, ..., RPB, MDV 
found header lines for 8 ‘geno’ fields: GT, GQ, ..., PL, DV 
Warning message:
In FUN(X[[i]], ...) :
  duplicate ID's in header will be forced to unique rownames

Vignette Results:
plus <- getAlleleCounts(reads, heterozygotePositions, strand="+",verbose=F) 
minus <- getAlleleCounts(reads, heterozygotePositions, strand="-",verbose=F) 
a.stranded <- ASEsetFromCountList( heterozygotePositions, countListPlus=plus, countListMinus=minus )
a.stranded 
## class: ASEset 
## dim: 3 20 
## metadata(0): 
## assays(4): countsPlus countsMinus mapBias phase ## rownames(3): chr17_79478287 chr17_79478331 chr17_79478334 
## rowRanges metadata column names(0): 
## colnames(20): ERR009097.bam ERR009102.bam ... ERR009160.bam 
## ERR009167.bam 
## colData names(0):
```
My Results:
```
> plus <- getAlleleCounts(reads, heterozygotePositions, strand="+",verbose=F)
> minus <- getAlleleCounts(reads, heterozygotePositions, strand="-",verbose=F)
> a.stranded <-
+ ASEsetFromCountList(
+ heterozygotePositions,
+ countListPlus=plus,
+ countListMinus=minus
+ )
> a.stranded
class: ASEset 
dim: 3 20 
exptData(0):
assays(5): countsPlus countsMinus countsUnknown mapBias phase
rownames(3): chr17_79478287 chr17_79478331 chr17_79478334
rowRanges metadata column names(0):
colnames(20): ERR009097.bam ERR009102.bam ... ERR009160.bam
  ERR009167.bam
colData names(0):
```
can you help me figure out what's wrong?
Thanks,
Diego 

Edit:  Here is the session info
```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
 [1] stats4    parallel  grid      stats     graphics  grDevices utils    
 [8] datasets  methods   base     

other attached packages:
 [1] AllelicImbalance_1.6.2    Gviz_1.12.1              
 [3] VariantAnnotation_1.14.13 GenomicAlignments_1.4.2  
 [5] Rsamtools_1.20.5          Biostrings_2.36.4        
 [7] XVector_0.8.0             GenomicRanges_1.20.8     
 [9] GenomeInfoDb_1.4.3        IRanges_2.2.9            
[11] S4Vectors_0.6.6           BiocGenerics_0.14.0      

loaded via a namespace (and not attached):
 [1] Formula_1.2-1          DBI_0.3.1              ggplot2_2.0.0         
 [4] futile.options_1.0.0   zlibbioc_1.14.0        bitops_1.0-6          
 [7] lattice_0.20-33        RSQLite_1.0.0          foreign_0.8-66        
[10] seqinr_3.1-3           rtracklayer_1.28.10    dichromat_2.0-0       
[13] biomaRt_2.24.1         BSgenome_1.36.3        Biobase_2.28.0        
[16] biovizBase_1.16.0      Rcpp_0.12.2            gridExtra_2.0.0       
[19] plyr_1.8.3             tools_3.2.2            RCurl_1.95-4.7        
[22] BiocParallel_1.2.22    lambda.r_1.1.7         futile.logger_1.4.1   
[25] scales_0.3.0           nnet_7.3-11            digest_0.6.8          
[28] gtable_0.1.2           latticeExtra_0.6-26    cluster_2.0.3         
[31] rpart_4.1-10           munsell_0.4.2          XML_3.98-1.3          
[34] colorspace_1.2-6       AnnotationDbi_1.30.1   Hmisc_3.17-1          
[37] splines_3.2.2          ade4_1.7-3             survival_2.38-3       
[40] RColorBrewer_1.1-2     GenomicFeatures_1.20.6 acepack_1.3-3.3       
[43] matrixStats_0.50.1   
```

**Comment by pappewaio** [comment] 2016-01-10 22:44
Hi Diego!

For the first question, try this order,
```
> genotype(a.simple) <- inferGenotypes(a.simple)
> ref(a.simple) <- randomRef(a.simple)
> alt(a.simple) <- inferAltAllele(a.simple)
```
The reason is that we need som genotypes to choose from to be able to use randomRef. And therefore it could be good to infer genotypes (from count data first). And to infer the alt allele we need to know which one is the ref allele, therefore running randomREF. 

For the second question,
I would not say it is wrong. Because you have both countsPlus and countsMinus(on the row above). To give the details, the countsUnknown assay is a relic from the earlier versions of AllelicImbalance. If you try to store stuff in there it will end up in the countsPlus assay anyway (if not providing plus and minus assays.). If providing all three the countsUnknown will be ditched, and only countsPlus and countsMinus kept. You might be right in that there is nothing explaining that behaviour. But as long as you don't mix stranded and non-stranded data you should be fine, which is something not recommended for several other technical package-specific reasons as well.. 

Jesper

**Comment by DM2016** [comment] 2016-01-11 18:07
Thank you Jesper,
I've just tried running the code again and this error has been eliminated.  However, I still am seeing the different results between the vignette:
## [,1] [,2] [,3] [,4]
## [1,] "T/G" "T/G" NA "T/G"
## [2,] "G/C" "G/C" "G/C" "G/C"
## [3,] "G/A" "G/A" "G/A" "G/A"

and my results:

individual1 individual2 individual3 individual4
rs2230159      "G/A"       "G/A"       NA          "G/A"      
chr17_79478331 "T/G"       "T/G"       "T/G"       "T/G"      
chr17_79478334 "C/G"       "C/G"       "C/G"       "C/G"

Additionally, I also see the following differences:

vignette: 
mean(refFrac)
## [1] 0.499586

#set ref allele
ref(a.stranded) <- c("G","T","C")
#binomial test
binom.test(a.stranded[,5:8], "+")
##                               chr17_79478287   chr17_79478331 chr17_79478334
## ERR009115.bam           NaN                  NaN                      NaN
## ERR009122.bam   0.7265625000          0.006610751       2.668457e-01
## ERR009126.bam    0.0004882813       0.107752144         1.907349e-06
## ERR009127.bam   0.2500000000        0.500000000         1.000000e+00

My results:

> mean(refFrac)
[1] 0.5013641
#set ref allele
ref(a.stranded) <- c("G","T","C")
#binomial test
binom.test(a.stranded[,5:8], "+")
     chr17_79478287 chr17_79478331 chr17_79478334
[1,]             NA                     NA                       NA
[2,]      0.7265625          0.006610751      0.2668457
[3,]             NA                0.107752144             NA
[4,]             NA                       NA                       NA

The mean(refFrac) values are different and the bottom row in the binomial test table is not calculated.  Is this as a result of randomREF?  Should I expect similar results when I use different datasets?

Thanks,
Diego

**Comment by pappewaio** [comment] 2016-01-12 14:22
You have discovered a bug in the inferAltAllele function, that was why ```genotype(a.simple)[,1:4]``` produced a result which did not match the vignette. That is now fixed in the bioconductor devel and release-3.2 versions.

And the reason why there could be a missmatch in comparison to the vignette is because the randomRef function is random and solely you can get a different result, when running it multiple times.

**Comment by pappewaio** [comment] 2016-01-12 14:35
Though, I can see that the change for the release-3.2 branch is not yet in the public repository. It might be so that there is a short delay for the release-3.2 branch to change.

**Comment by DM2016** [comment] 2016-01-12 15:53
Thanks, 
The rest of the example now works properly.  I would like to make sure of one more thing, in section 2.2, when you are establishing the pathway to VCF 

pathToVcf <- paste(pathToFiles,"/ERP000101.vcf",sep="")
VCF <- readVcf(pathToVcf,"hg19")
gr <- granges(VCF)

Does the second line refer to the hg19.fa that was created earlier or to something else?  I am now trying to use this code on a new dataset.

**Comment by pappewaio** [comment] 2016-01-12 18:00
Good that it works!
But, if you plan to use inferAltAllele on real data, then make sure you get the newest version of the package (AllelicImbalance_1.8.1 or the devel version). But I suspect that in the most cases you will already have the alternate allele information from the vcf file.

The second argument in the readVcf() function is just in this case a single string that tells which genome we are importing(not a path, previous created file or similar).

In my opinion not so important, but it does seem important to all the GenomicRanges and friends, where it most of the times is required. Anyhow, if you want the details, here is an excerpt from ?readVcf
```
    file: A ‘TabixFile’ instance or character() name of the VCF file to
          be processed. When ranges are specified in ‘param’, ‘file’
          must be a ‘TabixFile’.

          Use of the ‘TabixFile’ methods are encouraged as they are
          more efficient than the character() methods. See ?‘TabixFile’
          and ?‘indexTabix’ for help creating a ‘TabixFile’.

  genome: A ‘character’ or ‘Seqinfo’ object.

            • ‘character’: Genome identifier as a single string or
              named character vector. Names of the character vector
              correspond to chromosome names in the file. This
              identifier replaces the genome information in the VCF
              ‘Seqinfo’ (i.e., ‘seqinfo(vcf)’).

            • ‘Seqinfo’: When ‘genome’ is provided as a ‘Seqinfo’ it is
              propagated to the VCF output. If seqinfo information can
              be obtained from the file, (i.e.,
              seqinfo(scanVcfHeader(fl)) is not empty), the output
              ‘Seqinfo’ is a product of merging the two.

              If a param (i.e., ScanVcfParam) is used in the call to
              ‘readVcf’, the seqlevels of the param ranges must be
              present in ‘genome’.

```

**Comment by pappewaio** [comment] 2016-01-12 22:27
I am not sure if you already did, but now I can confirm that the updated version now is in the Bioconductor svn repo. Which is the one you can access by the command:
*user name: readonly*
*password: readonly*
```
svn co https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/AllelicImbalance
R CMD INSTALL AllelicImbalance
```

Still surprised that the update hasn't propagated to the standard biocLite() install yet... but guess they have to confirm with the build server that it doesn't throw any errors.

**Comment by pappewaio** [comment] 2016-04-05 06:52
Just wanted to confirm that the update is available through biocLite() now (and has been since long).

**Closed by pappewaio** 2016-04-05 06:52 UTC
